version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - nextcloud:/var/www/html
    depends_on:
      - nextcloud
    restart: always

  nextcloud:
    image: nextcloud:fpm-alpine
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: db
    volumes:
      - nextcloud:/var/www/html
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
    volumes:
      - db:/var/lib/mysql
    restart: always

volumes:
  nextcloud:
  db:
